### ISSUE TITLE
The location of the config files should be configurable

### ISSUE THREAD

**Issue by rbeukel** [DRIVER-EU/test-bed-rest-service#3]
Currently the REST adapter, automatically looks for the config files in the 'Config' directory that is in the folder from which the adapter is started. However, this requires quite a bit of hassle with Git stash/pop when a new version is available.

In my perspective it would be very helpful to provide an absolute path to a different config directory (containing the same files!) so those don't have to be 're-written' for every update of the adapter. Preferable this can be done with an extra parameter to the JAR file like:

```
"%JAVA_HOME%\java" -jar rest-testbed-adapter-1.2.4.jar -config="c:\driver_plus\config"
```

**Comment by thoobr** [comment]
Issue solved in release 1.2.5
testbed connection configuration can be provided with config parameter:
-config="c:\driver_plus\config"
The pathneeds to point to the config directory in which the config is located
Additionally if the port also needs do be changed this can be specified with the location of the application.propeties file:
-Dspring.config.location = C:\application.properties
